### ISSUE TITLE
Support the Handle pattern

### ISSUE THREAD

**Issue by etorreborre** [waddlaw/haskell-stack-trace-plugin#8]
In our code base we have many components defined like this:
```
data Component m = Component {
  function1 :: Int -> Text -> m Text,
  function2 :: Text -> Int -> m Double
}

newComponent :: Monad m => Dependency m -> Component m
newComponent dependency = Component {..} where
  function1 :: Int -> Text -> m Text
  function1 n t = do
    r <- callDependency dependency t
    pure (show n <> "-" <> r)

  function2 :: Text -> Int -> m Double
  function2 = panic "todo"
```

Since the plugin only adds `HasCallStack` constraints to top level functions we don't get a stacktrace for `function1` and `function2`. How hard would it be add?

**Comment by waddlaw** [comment]
@etorreborre I've implemented it, so can you please check if it works correctly in #11?
